sudo: required

language: php
php:
  - 7.1.9

env:
  - NODE_VERSION='8.11.3'

addons:
  apt:
    update: true
    packages:
      - composer
      - zip

before_install:
  - nvm install $NODE_VERSION

install:
  - yarn install

script:
  - yarn build
  - composer install
  - yarn zip

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: '*.zip'
  file_glob: true
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    branch: master
    tags: true